# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{timekeeper}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["atog"]
  s.date = %q{2009-10-01}
  s.description = %q{Timekeeper. Keeping track of your time.}
  s.email = %q{koen@atog.be}
  s.executables = ["tk", "tv"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/timekeeper.rb",
     "lib/timekeeper/keep.rb",
     "lib/timekeeper/timekeeper.rb",
     "lib/timekeeper/timeviewer.rb"
  ]
  s.homepage = %q{http://github.com/atog/timekeeper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Timekeeper. Keeping track of your time.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_runtime_dependency(%q<rufus-tokyo>, ["= 1.0.0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
      s.add_dependency(%q<rufus-tokyo>, ["= 1.0.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
    s.add_dependency(%q<rufus-tokyo>, ["= 1.0.0"])
  end
end
